import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { CompassCatalog } from "../src/catalog.js";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const compassRoot = path.resolve(appRoot, "../..");
const outputPath = path.join(appRoot, "worker", "generated-catalog.ts");
const catalog = new CompassCatalog(compassRoot);
const documents = [
  catalog.getProfile(),
  ...catalog.listSkills().map(skill => catalog.getSkill(skill.name))
];

const source = [
  "// Generated by scripts/generate-worker-catalog.ts. Do not edit.",
  "import type { CompassDocument } from \"../src/types.js\";",
  "",
  `export const embeddedDocuments: CompassDocument[] = ${JSON.stringify(documents, null, 2)};`,
  ""
].join("\n");

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, source, "utf8");
console.log(`Generated ${documents.length} Compass documents for Cloudflare Worker deployment.`);
